name: Integration Unit Tests

on:
  workflow_dispatch:
  pull_request:
    branches: 
    - master
    - develop
    - release/* 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1
      with:
        node-version: 14.x

    - name: "Install dependencies"
      run: |
        npm ci
        npm install -g vsce

    - name: "Set prepublish script for debug build"
      shell: pwsh
      run: |
        $packageManifest = Get-Content './package.json' | ConvertFrom-Json -NoEnumerate
        $packageManifest.scripts.'vscode:prepublish' = 'webpack --mode development'
        $packageManifest | ConvertTo-Json -Depth 100 | Out-File -FilePath './package.json' -Encoding 'utf8NoBOM'
        
    - name: Build debug
      run: |
        vsce package --out debug.vsix
        
    - name: Test
      uses: GabrielBB/xvfb-action@v1.0
      with:
        run: npm test
