name: Integration Unit Tests

on:
  workflow_dispatch:
  pull_request:
    branches: 
    - master
    - develop
    - release/* 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1
      with:
        node-version: 14.x

    - name: Install Node Dependencies on API
      run: |
        npm install
        
    - name: Install Node Dependencies on API
      run: |
        npm test